spring.application.name=taskmanagement

spring.r2dbc.url=${R2DBC_URL}
spring.r2dbc.username=${R2DBC_USERNAME}
spring.r2dbc.password=${R2DBC_PASSWORD}

server.port=${SERVER_PORT:8080}

spring.security.enabled=false
logging.level.org.springframework.security=DEBUG


